const RalPalette = [{
    RAL: "RAL1000",
    RGB: "201-187-136",
    HEX: "#CDBA88",
    German: "Grünbeige",
    English: "Green beige",
    French: "Beige vert",
    Spanish: "Beige verdoso",
    Italian: "Beige verdastro",
    Nederlands: "Groenbeige"
  },
  {
    RAL: "RAL1001",
    RGB: "204-176-131",
    HEX: "#D0B084",
    German: "Beige",
    English: "Beige",
    French: "Beige",
    Spanish: "Beige",
    Italian: "Beige",
    Nederlands: "Beige"
  },
  {
    RAL: "RAL1002",
    RGB: "205-170-109",
    HEX: "#D2AA6D",
    German: "Sandgelb",
    English: "Sand yellow",
    French: "Jaune sable",
    Spanish: "Amarillo arena",
    Italian: "Giallo sabbia",
    Nederlands: "Zandgeel"
  },
  {
    RAL: "RAL1003",
    RGB: "242-169-0",
    HEX: "#F9A800",
    German: "Signalgelb",
    English: "Signal yellow",
    French: "Jaune de sécurité",
    Spanish: "Amarillo señales",
    Italian: "Giallo segnale",
    Nederlands: "Signaalgeel"
  },
  {
    RAL: "RAL1004",
    RGB: "221-159-0",
    HEX: "#E49E00",
    German: "Goldgelb",
    English: "Golden yellow",
    French: "Jaune or",
    Spanish: "Amarillo oro",
    Italian: "Giallo oro",
    Nederlands: "Goudgeel"
  },
  {
    RAL: "RAL1005",
    RGB: "197-143-0",
    HEX: "#CB8E00",
    German: "Honiggelb",
    English: "Honey yellow",
    French: "Jaune miel",
    Spanish: "Amarillo miel",
    Italian: "Giallo miele",
    Nederlands: "Honinggeel"
  },
  {
    RAL: "RAL1006",
    RGB: "219-145-0",
    HEX: "#E29000",
    German: "Maisgelb",
    English: "Maize yellow",
    French: "Jaune maïs",
    Spanish: "Amarillo maiz",
    Italian: "Giallo polenta",
    Nederlands: "Maisgeel"
  },
  {
    RAL: "RAL1007",
    RGB: "226-141-0",
    HEX: "#E88C00",
    German: "Narzissengelb",
    English: "Daffodil yellow",
    French: "Jaune narcisse",
    Spanish: "Amarillo narciso",
    Italian: "Giallo narciso",
    Nederlands: "Narcissengeel"
  },
  {
    RAL: "RAL1011",
    RGB: "171-129-79",
    HEX: "#AF804F",
    German: "Braunbeige",
    English: "Brown beige",
    French: "Beige brun",
    Spanish: "Beige pardo",
    Italian: "Beige marrone",
    Nederlands: "Bruinbeige"
  },
  {
    RAL: "RAL1012",
    RGB: "214-176-37",
    HEX: "#DDAF27",
    German: "Zitronengelb",
    English: "Lemon yellow",
    French: "Jaune citron",
    Spanish: "Amarillo limón",
    Italian: "Giallo limone",
    Nederlands: "Citroengeel"
  },
  {
    RAL: "RAL1013",
    RGB: "225-218-199",
    HEX: "#E3D9C6",
    German: "Perlweiß",
    English: "Oyster white",
    French: "Blanc perlé",
    Spanish: "Blanco perla",
    Italian: "Bianco perla",
    Nederlands: "Parelwit"
  },
  {
    RAL: "RAL1014",
    RGB: "217-197-154",
    HEX: "#DDC49A",
    German: "Elfenbein",
    English: "Ivory",
    French: "Ivoire",
    Spanish: "Marfil",
    Italian: "Avorio",
    Nederlands: "Ivoorkleurig"
  },
  {
    RAL: "RAL1015",
    RGB: "227-211-181",
    HEX: "#E6D2B5",
    German: "Hellelfenbein",
    English: "Light ivory",
    French: "Ivoire clair",
    Spanish: "Marfil claro",
    Italian: "Avorio chiaro",
    Nederlands: "Licht ivoorkleurig"
  },
  {
    RAL: "RAL1016",
    RGB: "232-222-53",
    HEX: "#F1DD38",
    German: "Schwefelgelb",
    English: "Sulfur yellow",
    French: "Jaune soufre",
    Spanish: "Amarillo azufre",
    Italian: "Giallo zolfo",
    Nederlands: "Zwavelgeel"
  },
  {
    RAL: "RAL1017",
    RGB: "240-170-80",
    HEX: "#F6A950",
    German: "Safrangelb",
    English: "Saffron yellow",
    French: "Jaune safran",
    Spanish: "Amarillo azafrán",
    Italian: "Giallo zafferano",
    Nederlands: "Saffraangeel"
  },
  {
    RAL: "RAL1018",
    RGB: "242-203-46",
    HEX: "#FACA30",
    German: "Zinkgelb",
    English: "Zinc yellow",
    French: "Jaune zinc",
    Spanish: "Amarillo de zinc",
    Italian: "Giallo zinco",
    Nederlands: "Zinkgeel"
  },
  {
    RAL: "RAL1019",
    RGB: "162-143-122",
    HEX: "#A48F7A",
    German: "Graubeige",
    English: "Grey beige",
    French: "Beige gris",
    Spanish: "Beige agrisado",
    Italian: "Beige grigiastro",
    Nederlands: "Grijsbeige"
  },
  {
    RAL: "RAL1020",
    RGB: "157-143-101",
    HEX: "#A08F65",
    German: "Olivgelb",
    English: "Olive yellow",
    French: "Jaune olive",
    Spanish: "Amarillo oliva",
    Italian: "Giallo olivastro",
    Nederlands: "Olijfgeel"
  },
  {
    RAL: "RAL1021",
    RGB: "238-183-0",
    HEX: "#F6B600",
    German: "Rapsgelb",
    English: "Rape yellow",
    French: "Jaune colza",
    Spanish: "Amarillo colza",
    Italian: "Giallo navone",
    Nederlands: "Koolzaadgeel"
  },
  {
    RAL: "RAL1023",
    RGB: "239-183-0",
    HEX: "#F7B500",
    German: "Verkehrsgelb",
    English: "Traffic yellow",
    French: "Jaune signalisation",
    Spanish: "Amarillo tráfico",
    Italian: "Giallo traffico",
    Nederlands: "Verkeersgeel"
  },
  {
    RAL: "RAL1024",
    RGB: "181-144-75",
    HEX: "#BA8F4C",
    German: "Ockergelb",
    English: "Ochre yellow",
    French: "Jaune ocre",
    Spanish: "Amarillo ocre",
    Italian: "Giallo ocra",
    Nederlands: "Okergeel"
  },
  {
    RAL: "RAL1026",
    RGB: "255-255-0",
    HEX: "#FFFF00",
    German: "Leuchtgelb",
    English: "Luminous yellow",
    French: "Jaune brillant",
    Spanish: "Amarillo brillante",
    Italian: "Giallo brillante",
    Nederlands: "Briljantgeel"
  },
  {
    RAL: "RAL1027",
    RGB: "162-128-12",
    HEX: "#A77F0E",
    German: "Currygelb",
    English: "Curry",
    French: "Jaune curry",
    Spanish: "Amarillo curry",
    Italian: "Giallo curry",
    Nederlands: "Kerriegeel"
  },
  {
    RAL: "RAL1028",
    RGB: "255-156-0",
    HEX: "#FF9B00",
    German: "Melonengelb",
    English: "Melon yellow",
    French: "Jaune melon",
    Spanish: "Amarillo melón",
    Italian: "Giallo melone",
    Nederlands: "Meloengeel"
  },
  {
    RAL: "RAL1032",
    RGB: "219-164-0",
    HEX: "#E2A300",
    German: "Ginstergelb",
    English: "Broom yellow",
    French: "Jaune genêt",
    Spanish: "Amarillo retama",
    Italian: "Giallo scopa",
    Nederlands: "Bremgeel"
  },
  {
    RAL: "RAL1033",
    RGB: "243-155-27",
    HEX: "#F99A1C",
    German: "Dahliengelb",
    English: "Dahlia yellow",
    French: "Jaune dahlia",
    Spanish: "Amarillo dalia",
    Italian: "Giallo dahlien",
    Nederlands: "Dahliageel"
  },
  {
    RAL: "RAL1034",
    RGB: "230-157-81",
    HEX: "#EB9C52",
    German: "Pastellgelb",
    English: "Pastel yellow",
    French: "Jaune pastel",
    Spanish: "Amarillo pastel",
    Italian: "Giallo pastello",
    Nederlands: "Pastelgeel"
  },
  {
    RAL: "RAL1035",
    RGB: "142-131-112",
    HEX: "#908370",
    German: "Perlbeige",
    English: "Pearl beige",
    French: "Beige nacré",
    Spanish: "Beige perlado",
    Italian: "Beige perlato",
    Nederlands: "Parelmoergrijs"
  },
  {
    RAL: "RAL1036",
    RGB: "125-101-63",
    HEX: "#80643F",
    German: "Perlgold",
    English: "Pearl gold",
    French: "Or nacré",
    Spanish: "Oro perlado",
    Italian: "Oro perlato",
    Nederlands: "Parelmoergoud"
  },
  {
    RAL: "RAL1037",
    RGB: "234-147-0",
    HEX: "#F09200",
    German: "Sonnengelb",
    English: "Sun yellow",
    French: "Jaune soleil",
    Spanish: "Amarillo sol",
    Italian: "Giallo sole",
    Nederlands: "Zonnegeel"
  },
  {
    RAL: "RAL2000",
    RGB: "213-111-0",
    HEX: "#DD7907",
    German: "Gelborange",
    English: "Yellow orange",
    French: "Orangé jaune",
    Spanish: "Amarillo naranja",
    Italian: "Arancio giallastro",
    Nederlands: "Geeloranje"
  },
  {
    RAL: "RAL2001",
    RGB: "182-72-28",
    HEX: "#BE4E20",
    German: "Rotorange",
    English: "Red orange",
    French: "Orangé rouge",
    Spanish: "Rojo anaranjado",
    Italian: "Arancio rossastro",
    Nederlands: "Roodoranje"
  },
  {
    RAL: "RAL2002",
    RGB: "188-56-35",
    HEX: "#C63927",
    German: "Blutorange",
    English: "Vermilion",
    French: "Orangé sang",
    Spanish: "Naranja sanguineo",
    Italian: "Arancio sanguigno",
    Nederlands: "Vermiljoen"
  },
  {
    RAL: "RAL2003",
    RGB: "241-120-41",
    HEX: "#FA842B",
    German: "Pastellorange",
    English: "Pastel orange",
    French: "Orangé pastel",
    Spanish: "Naranja pálido",
    Italian: "Arancio pastello",
    Nederlands: "Pasteloranje"
  },
  {
    RAL: "RAL2004",
    RGB: "222-83-6",
    HEX: "#E75B12",
    German: "Reinorange",
    English: "Pure orange",
    French: "Orangé pur",
    Spanish: "Naranja puro",
    Italian: "Arancio puro",
    Nederlands: "Zuiver oranje"
  },
  {
    RAL: "RAL2005",
    RGB: "255-75-17",
    HEX: "#FF2300",
    German: "Leuchtorange",
    English: "Luminous orange",
    French: "Orangé brillant",
    Spanish: "Naranja brillante",
    Italian: "Arancio brillante",
    Nederlands: "Briljant oranje"
  },
  {
    RAL: "RAL2007",
    RGB: "255-183-0",
    HEX: "#FFA421",
    German: "Leuchthellorange",
    English: "Luminous bright orange",
    French: "Orangé clair rillant",
    Spanish: "Naranja claro brillante",
    Italian: "Arancio chiaro brillante",
    Nederlands: "Briljant lichtoranje"
  },
  {
    RAL: "RAL2008",
    RGB: "232-107-34",
    HEX: "#F3752C",
    German: "Hellrotorange",
    English: "Bright red orange",
    French: "Orangé rouge clair",
    Spanish: "Rojo claro anaranjado",
    Italian: "Rosso arancio chiaro",
    Nederlands: "Licht roodoranje"
  },
  {
    RAL: "RAL2009",
    RGB: "218-83-10",
    HEX: "#E15501",
    German: "Verkehrsorange",
    English: "Traffic orange",
    French: "Orangé signalisation",
    Spanish: "Naranja tráfico",
    Italian: "Arancio traffico",
    Nederlands: "Verkeersoranje"
  },
  {
    RAL: "RAL2010",
    RGB: "204-93-41",
    HEX: "#D4652F",
    German: "Signalorange",
    English: "Signal orange",
    French: "Orangé de sécurité",
    Spanish: "Naranja señales",
    Italian: "Arancio segnale",
    Nederlands: "Signaaloranje"
  },
  {
    RAL: "RAL2011",
    RGB: "221-110-15",
    HEX: "#EC7C25",
    German: "Tieforange",
    English: "Deep orange",
    French: "Orangé foncé",
    Spanish: "Naranja intenso",
    Italian: "Arancio profondo",
    Nederlands: "Dieporanje"
  },
  {
    RAL: "RAL2012",
    RGB: "209-101-78",
    HEX: "#DB6A50",
    German: "Lachsorange",
    English: "Salmon range",
    French: "Orangé saumon",
    Spanish: "Naranja salmón",
    Italian: "Arancio salmone",
    Nederlands: "Zalmoranje"
  },
  {
    RAL: "RAL2013",
    RGB: "143-62-38",
    HEX: "#954527",
    German: "Perlorange",
    English: "Pearl orange",
    French: "Orangé nacré",
    Spanish: "Naranja perlado",
    Italian: "Arancio perlato",
    Nederlands: "Parelmoeroranje"
  },
  {
    RAL: "RAL3000",
    RGB: "164-40-33",
    HEX: "#AB2524",
    German: "Feuerrot",
    English: "Flame red",
    French: "Rouge feu",
    Spanish: "Rojo vivo",
    Italian: "Rosso fuoco",
    Nederlands: "Vuurrood"
  },
  {
    RAL: "RAL3001",
    RGB: "152-35-35",
    HEX: "#A02128",
    German: "Signalrot",
    English: "Signal red",
    French: "Rouge de sécurité",
    Spanish: "Rojo señales",
    Italian: "Rosso  segnale",
    Nederlands: "Signaalrood"
  },
  {
    RAL: "RAL3002",
    RGB: "152-34-34",
    HEX: "#A1232B",
    German: "Karminrot",
    English: "Carmine red",
    French: "Rouge carmin",
    Spanish: "Rojo carmin",
    Italian: "Rosso carminio",
    Nederlands: "Karmijnrood"
  },
  {
    RAL: "RAL3003",
    RGB: "132-25-34",
    HEX: "#8D1D2C",
    German: "Rubinrot",
    English: "Ruby red",
    French: "Rouge rubis",
    Spanish: "Rojo rubí",
    Italian: "Rosso rubino",
    Nederlands: "Robijnrood"
  },
  {
    RAL: "RAL3004",
    RGB: "105-27-35",
    HEX: "#701F29",
    German: "Purpurrot",
    English: "Purple red",
    French: "Rouge pourpre",
    Spanish: "Rojo purpura",
    Italian: "Rosso porpora",
    Nederlands: "Purperrood"
  },
  {
    RAL: "RAL3005",
    RGB: "88-24-31",
    HEX: "#5E2028",
    German: "Weinrot",
    English: "Wine red",
    French: "Rouge vin",
    Spanish: "Rojo vino",
    Italian: "Rosso vino",
    Nederlands: "Wijnrood"
  },
  {
    RAL: "RAL3007",
    RGB: "61-32-34",
    HEX: "#402225",
    German: "Schwarzrot",
    English: "Black red",
    French: "Rouge noir",
    Spanish: "Rojo negruzco",
    Italian: "Rosso nerastro",
    Nederlands: "Zwartrood"
  },
  {
    RAL: "RAL3009",
    RGB: "102-48-41",
    HEX: "#703731",
    German: "Oxidrot",
    English: "Oxide red",
    French: "Rouge oxyde",
    Spanish: "Rojo óxido",
    Italian: "Rosso  ossido",
    Nederlands: "Oxyderood"
  },
  {
    RAL: "RAL3011",
    RGB: "119-36-36",
    HEX: "#7E292C",
    German: "Braunrot",
    English: "Brown red",
    French: "Rouge brun",
    Spanish: "Rojo pardo",
    Italian: "Rosso marrone",
    Nederlands: "Bruinrood"
  },
  {
    RAL: "RAL3012",
    RGB: "194-133-109",
    HEX: "#CB8D73",
    German: "Beigerot",
    English: "Beige red",
    French: "Rouge beige",
    Spanish: "Rojo beige",
    Italian: "Rosso beige",
    Nederlands: "Beigerood"
  },
  {
    RAL: "RAL3013",
    RGB: "149-46-37",
    HEX: "#9C322E",
    German: "Tomatenrot",
    English: "Tomato red",
    French: "Rouge tomate",
    Spanish: "Rojo tomate",
    Italian: "Rosso pomodoro",
    Nederlands: "Tomaatrood"
  },
  {
    RAL: "RAL3014",
    RGB: "201-115-117",
    HEX: "#D47479",
    German: "Altrosa",
    English: "Antique pink",
    French: "Vieux rose",
    Spanish: "Rojo viejo",
    Italian: "Rosa antico",
    Nederlands: "Oudroze"
  },
  {
    RAL: "RAL3015",
    RGB: "215-160-166",
    HEX: "#E1A6AD",
    German: "Hellrosa",
    English: "Light pink",
    French: "Rose clair",
    Spanish: "Rosa claro",
    Italian: "Rosa chiaro",
    Nederlands: "Lichtroze"
  },
  {
    RAL: "RAL3016",
    RGB: "164-60-48",
    HEX: "#AC4034",
    German: "Korallenrot",
    English: "Cored",
    French: "Rouge corail",
    Spanish: "Rojo coral",
    Italian: "Rosso corallo",
    Nederlands: "Koraalrood"
  },
  {
    RAL: "RAL3017",
    RGB: "200-84-93",
    HEX: "#D3545F",
    German: "Rosé",
    English: "Rose",
    French: "Rosé",
    Spanish: "Rosa",
    Italian: "Rosato",
    Nederlands: "Bleekrood"
  },
  {
    RAL: "RAL3018",
    RGB: "196-62-74",
    HEX: "#D14152",
    German: "Erdbeerrot",
    English: "Strawberry red",
    French: "Rouge fraise",
    Spanish: "Rojo fresa",
    Italian: "Rosso fragola",
    Nederlands: "Aardbeirood"
  },
  {
    RAL: "RAL3020",
    RGB: "184-29-19",
    HEX: "#C1121C",
    German: "Verkehrsrot",
    English: "Traffic red",
    French: "Rouge signalisation",
    Spanish: "Rojo tráfico",
    Italian: "Rosso traffico",
    Nederlands: "Verkeersrood"
  },
  {
    RAL: "RAL3022",
    RGB: "204-105-85",
    HEX: "#D56D56",
    German: "Lachsrot",
    English: "Salmon pink",
    French: "Rouge saumon",
    Spanish: "Rojo salmón",
    Italian: "Rosso salmone",
    Nederlands: "Zalmrood"
  },
  {
    RAL: "RAL3024",
    RGB: "255-42-36",
    HEX: "#F70000",
    German: "Leuchtrot",
    English: "Luminous red",
    French: "Rouge brillant",
    Spanish: "Rojo brillante",
    Italian: "Rosso brillante",
    Nederlands: "Briljantrood"
  },
  {
    RAL: "RAL3026",
    RGB: "255-38-32",
    HEX: "#FF0000",
    German: "Leuchthellrot",
    English: "Luminous bright red",
    French: "Rouge clair brillant",
    Spanish: "Rojo claro brillante",
    Italian: "Rosso chiaro brillante",
    Nederlands: "Briljant lichtrood"
  },
  {
    RAL: "RAL3027",
    RGB: "169-38-61",
    HEX: "#B42041",
    German: "Himbeerrot",
    English: "Raspberry red",
    French: "Rouge framboise",
    Spanish: "Rojo frambuesa",
    Italian: "Rosso lampone",
    Nederlands: "Framboosrood"
  },
  {
    RAL: "RAL3028",
    RGB: "201-43-38",
    HEX: "#E72512",
    German: "Reinrot",
    English: "Pure  red",
    French: "Rouge puro",
    Spanish: "Rojo puro",
    Italian: "Rosso puro",
    Nederlands: "Zuiverrood"
  },
  {
    RAL: "RAL3031",
    RGB: "164-51-56",
    HEX: "#AC323B",
    German: "Orientrot",
    English: "Orient red",
    French: "Rouge oriental",
    Spanish: "Rojo oriente",
    Italian: "Rosso oriente",
    Nederlands: "Oriëntrood"
  },
  {
    RAL: "RAL3032",
    RGB: "110-28-36",
    HEX: "#711521",
    German: "Perlrubinrot",
    English: "Pearl ruby red",
    French: "Rouge rubis nacré",
    Spanish: "Rojo rubí perlado",
    Italian: "Rosso rubino perlato",
    Nederlands: "Parelmoer-donkerrood"
  },
  {
    RAL: "RAL3033",
    RGB: "162-57-46",
    HEX: "#B24C43",
    German: "Perlrosa",
    English: "Pearl pink",
    French: "Rose nacré",
    Spanish: "Rosa perlado",
    Italian: "Rosa perlato",
    Nederlands: "Parelmoer-lichtrood"
  },
  {
    RAL: "RAL4001",
    RGB: "131-96-131",
    HEX: "#8A5A83",
    German: "Rotlila",
    English: "Red lilac",
    French: "Lilas rouge",
    Spanish: "Rojo lila",
    Italian: "Lilla rossastro",
    Nederlands: "Roodlila"
  },
  {
    RAL: "RAL4002",
    RGB: "140-60-75",
    HEX: "#933D50",
    German: "Rotviolett",
    English: "Red violet",
    French: "Violet rouge",
    Spanish: "Rojo violeta",
    Italian: "Viola rossastro",
    Nederlands: "Roodpaars"
  },
  {
    RAL: "RAL4003",
    RGB: "196-96-140",
    HEX: "#D15B8F",
    German: "Erikaviolett",
    English: "Heather violet",
    French: "Violet bruyère",
    Spanish: "Violeta érica",
    Italian: "Viola erica",
    Nederlands: "Heidepaars"
  },
  {
    RAL: "RAL4004",
    RGB: "100-29-57",
    HEX: "#691639",
    German: "Bordeauxviolett",
    English: "Claret violet",
    French: "Violet bordeaux",
    Spanish: "Burdeos",
    Italian: "Viola bordeaux",
    Nederlands: "Bordeauxpaars"
  },
  {
    RAL: "RAL4005",
    RGB: "123-103-154",
    HEX: "#83639D",
    German: "Blaulila",
    English: "Blue lilac",
    French: "Lilas bleu",
    Spanish: "Lila azulado",
    Italian: "Lilla bluastro",
    Nederlands: "Blauwlila"
  },
  {
    RAL: "RAL4006",
    RGB: "145-48-115",
    HEX: "#992572",
    German: "Verkehrspurpur",
    English: "Traffic purple",
    French: "Pourpre signalisation",
    Spanish: "Púrpurá tráfico",
    Italian: "Porpora traffico",
    Nederlands: "Verkeerspurper"
  },
  {
    RAL: "RAL4007",
    RGB: "71-36-60",
    HEX: "#4A203B",
    German: "Purpurviolett",
    English: "Purple violet",
    French: "Violet pourpre",
    Spanish: "Violeta púrpura",
    Italian: "Porpora violetto",
    Nederlands: "Purperviolet"
  },
  {
    RAL: "RAL4008",
    RGB: "135-75-131",
    HEX: "#904684",
    German: "Signalviolett",
    English: "Signal violet",
    French: "Violet de sécurité",
    Spanish: "Violeta señales",
    Italian: "Violetto segnale",
    Nederlands: "Signaalviolet"
  },
  {
    RAL: "RAL4009",
    RGB: "157-133-146",
    HEX: "#A38995",
    German: "Pastellviolett",
    English: "Pastel violet",
    French: "Violet pastel",
    Spanish: "Violeta pastel",
    Italian: "Violetto pastello",
    Nederlands: "Pastelviolet"
  },
  {
    RAL: "RAL4010",
    RGB: "187-62-119",
    HEX: "#C63678",
    German: "Telemagenta",
    English: "Telemagenta",
    French: "Telemagenta",
    Spanish: "Magenta tele",
    Italian: "Tele Magenta",
    Nederlands: "Telemagenta"
  },
  {
    RAL: "RAL4011",
    RGB: "113-98-135",
    HEX: "#8773A1",
    German: "Perlviolett",
    English: "Pearl violet",
    French: "Violet nacré",
    Spanish: "Violeta perlado",
    Italian: "Violetto perlato",
    Nederlands: "Parelmoer-donkerviolet"
  },
  {
    RAL: "RAL4012",
    RGB: "109-107-127",
    HEX: "#6B6880",
    German: "Perlbrombeer",
    English: "Pearl black berry",
    French: "Mûre nacré",
    Spanish: "Morado perlado",
    Italian: "Mora perlato",
    Nederlands: "Parelmoer-lichtviolet"
  },
  {
    RAL: "RAL5000",
    RGB: "56-78-111",
    HEX: "#384C70",
    German: "Violettblau",
    English: "Violet blue",
    French: "Bleu violet",
    Spanish: "Azul violeta",
    Italian: "Blu violaceo",
    Nederlands: "Paarsblauw"
  },
  {
    RAL: "RAL5001",
    RGB: "29-76-100",
    HEX: "#1F4764",
    German: "Grünblau",
    English: "Green blue",
    French: "Bleu vert",
    Spanish: "Azul verdoso",
    Italian: "Blu verdastro",
    Nederlands: "Groenblauw"
  },
  {
    RAL: "RAL5002",
    RGB: "30-54-123",
    HEX: "#2B2C7C",
    German: "Ultramarinblau",
    English: "Ultramarine blue",
    French: "Bleu outremer",
    Spanish: "Azul ultramar",
    Italian: "Blu oltremare",
    Nederlands: "Ultramarijnblauw"
  },
  {
    RAL: "RAL5003",
    RGB: "38-56-85",
    HEX: "#2A3756",
    German: "Saphirblau",
    English: "Saphire blue",
    French: "Bleu saphir",
    Spanish: "Azul zafiro",
    Italian: "Blu zaffiro",
    Nederlands: "Saffierblauw"
  },
  {
    RAL: "RAL5004",
    RGB: "26-30-40",
    HEX: "#1D1F2A",
    German: "Schwarzblau",
    English: "Black blue",
    French: "Bleu noir",
    Spanish: "Azul negruzco",
    Italian: "Blu nerastro",
    Nederlands: "Zwartblauw"
  },
  {
    RAL: "RAL5005",
    RGB: "0-81-135",
    HEX: "#154889",
    German: "Signalblau",
    English: "Signal blue",
    French: "Bleu de sécurité",
    Spanish: "Azul señales",
    Italian: "Blu segnale",
    Nederlands: "Signaalblauw"
  },
  {
    RAL: "RAL5007",
    RGB: "66-106-140",
    HEX: "#41678D",
    German: "Brillantblau",
    English: "Brillant blue",
    French: "Bleu brillant",
    Spanish: "Azul brillante",
    Italian: "Blu brillante",
    Nederlands: "Briljantblauw"
  },
  {
    RAL: "RAL5008",
    RGB: "45-58-68",
    HEX: "#313C48",
    German: "Graublau",
    English: "Grey blue",
    French: "Bleu gris",
    Spanish: "Azul grisáceo",
    Italian: "Blu grigiastro",
    Nederlands: "Grijsblauw"
  },
  {
    RAL: "RAL5009",
    RGB: "45-94-120",
    HEX: "#2E5978",
    German: "Azurblau",
    English: "Azure blue",
    French: "Bleu azur",
    Spanish: "Azul azur",
    Italian: "Blu  azzurro",
    Nederlands: "Azuurblauw"
  },
  {
    RAL: "RAL5010",
    RGB: "0-78-124",
    HEX: "#13447C",
    German: "Enzianblau",
    English: "Gentian blue",
    French: "Bleu gentiane",
    Spanish: "Azul genciana",
    Italian: "Blu  genziana",
    Nederlands: "Gentiaanblauw"
  },
  {
    RAL: "RAL5011",
    RGB: "30-43-61",
    HEX: "#232C3F",
    German: "Stahlblau",
    English: "Steel blue",
    French: "Bleu acier",
    Spanish: "Azul acero",
    Italian: "Blu acciaio",
    Nederlands: "Staalblauw"
  },
  {
    RAL: "RAL5012",
    RGB: "46-136-182",
    HEX: "#3481B8",
    German: "Lichtblau",
    English: "Light blue",
    French: "Bleu clair",
    Spanish: "Azul luminoso",
    Italian: "Blu luce",
    Nederlands: "Lichtblauw"
  },
  {
    RAL: "RAL5013",
    RGB: "34-48-83",
    HEX: "#232D53",
    German: "Kobaltblau",
    English: "Cobalt blue",
    French: "Bleu cobalt",
    Spanish: "Azul cobalto",
    Italian: "Blu cobalto",
    Nederlands: "Kobaltblauw"
  },
  {
    RAL: "RAL5014",
    RGB: "104-124-150",
    HEX: "#6C7C98",
    German: "Taubenblau",
    English: "Pigeon blue",
    French: "Bleu pigeon",
    Spanish: "Azul olombino",
    Italian: "Blu colomba",
    Nederlands: "Duifblauw"
  },
  {
    RAL: "RAL5015",
    RGB: "11-123-176",
    HEX: "#2874B2",
    German: "Himmelblau",
    English: "Sky blue",
    French: "Bleu ciel",
    Spanish: "Azul celeste",
    Italian: "Blu cielo",
    Nederlands: "Hemelsblauw"
  },
  {
    RAL: "RAL5017",
    RGB: "0-90-140",
    HEX: "#0E518D",
    German: "Verkehrsblau",
    English: "Traffic blue",
    French: "Bleu signalisation",
    Spanish: "Azul tráfico",
    Italian: "Blu traffico",
    Nederlands: "Verkeersblauw"
  },
  {
    RAL: "RAL5018",
    RGB: "27-139-140",
    HEX: "#21888F",
    German: "Türkisblau",
    English: "Turquoise blue",
    French: "Bleu turquoise",
    Spanish: "Azul turquesa",
    Italian: "Blu turchese",
    Nederlands: "Turkooisblauw"
  },
  {
    RAL: "RAL5019",
    RGB: "15-93-132",
    HEX: "#1A5784",
    German: "Capriblau",
    English: "Capri blue",
    French: "Bleu capri",
    Spanish: "Azul capri",
    Italian: "Blu capri",
    Nederlands: "Capriblauw"
  },
  {
    RAL: "RAL5020",
    RGB: "0-65-75",
    HEX: "#0B4151",
    German: "Ozeanblau",
    English: "Ocean blue",
    French: "Bleu océan",
    Spanish: "Azul oceano",
    Italian: "Blu oceano",
    Nederlands: "Oceaanblauw"
  },
  {
    RAL: "RAL5021",
    RGB: "0-117-119",
    HEX: "#07737A",
    German: "Wasserblau",
    English: "Water blue",
    French: "Bleu d’eau",
    Spanish: "Azul agua",
    Italian: "Blu acqua",
    Nederlands: "Waterblauw"
  },
  {
    RAL: "RAL5022",
    RGB: "43-44-90",
    HEX: "#2F2A5A",
    German: "Nachtblau",
    English: "Night blue",
    French: "Bleu nocturne",
    Spanish: "Azul noche",
    Italian: "Blu notte",
    Nederlands: "Nachtblauw"
  },
  {
    RAL: "RAL5023",
    RGB: "74-104-141",
    HEX: "#4D668E",
    German: "Fernblau",
    English: "Distant blue",
    French: "Bleu distant",
    Spanish: "Azul lejanía",
    Italian: "Blu distante",
    Nederlands: "Verblauw"
  },
  {
    RAL: "RAL5024",
    RGB: "103-146-172",
    HEX: "#6A93B0",
    German: "Pastellblau",
    English: "Pastel blue",
    French: "Bleu pastel",
    Spanish: "Azul pastel",
    Italian: "Blu pastello",
    Nederlands: "Pastelblauw"
  },
  {
    RAL: "RAL5025",
    RGB: "44-105-124",
    HEX: "#296478",
    German: "Perlenzian",
    English: "Pearl gentian blue",
    French: "Gentiane nacré",
    Spanish: "Gencian perlado",
    Italian: "Blu genziana perlato",
    Nederlands: "Parelmoerblauw"
  },
  {
    RAL: "RAL5026",
    RGB: "27-47-82",
    HEX: "#102C54",
    German: "Perlnachtblau",
    English: "Pearl night blue",
    French: "Bleu nuit nacré",
    Spanish: "Azul noche perlado",
    Italian: "Blu notte perlato",
    Nederlands: "Parelmoer-nachtblauw"
  },
  {
    RAL: "RAL6000",
    RGB: "59-116-96",
    HEX: "#327662",
    German: "Patinagrün",
    English: "Patina green",
    French: "Vert patine",
    Spanish: "Verde patina",
    Italian: "Verde patina",
    Nederlands: "Patinagroen"
  },
  {
    RAL: "RAL6001",
    RGB: "49-104-52",
    HEX: "#28713E",
    German: "Smaragdgrün",
    English: "Emerald green",
    French: "Vert émeraude",
    Spanish: "Verde esmeralda",
    Italian: "Verde smeraldo",
    Nederlands: "Smaragdgroen"
  },
  {
    RAL: "RAL6002",
    RGB: "45-90-39",
    HEX: "#276235",
    German: "Laubgrün",
    English: "Leaf green",
    French: "Vert feuillage",
    Spanish: "Verde hoja",
    Italian: "Verde foglia",
    Nederlands: "Loofgroen"
  },
  {
    RAL: "RAL6003",
    RGB: "78-83-59",
    HEX: "#4B573E",
    German: "Olivgrün",
    English: "Olive green",
    French: "Vert olive",
    Spanish: "Verde oliva",
    Italian: "Verde oliva",
    Nederlands: "Olijfgroen"
  },
  {
    RAL: "RAL6004",
    RGB: "8-68-66",
    HEX: "#0E4243",
    German: "Blaugrün",
    English: "Blue green",
    French: "Vert bleu",
    Spanish: "Verde azulado",
    Italian: "Verde bluastro",
    Nederlands: "Blauwgroen"
  },
  {
    RAL: "RAL6005",
    RGB: "17-66-50",
    HEX: "#0F4336",
    German: "Moosgrün",
    English: "Moss green",
    French: "Vert mousse",
    Spanish: "Verde musgo",
    Italian: "Verde muschio",
    Nederlands: "Mosgroen"
  },
  {
    RAL: "RAL6006",
    RGB: "59-57-46",
    HEX: "#40433B",
    German: "Grauoliv",
    English: "Grey olive",
    French: "Olive gris",
    Spanish: "Oliva grisáceo",
    Italian: "Oliva grigiastro",
    Nederlands: "Grijs olijfgroen"
  },
  {
    RAL: "RAL6007",
    RGB: "42-50-34",
    HEX: "#283424",
    German: "Flaschengrün",
    English: "Bottle green",
    French: "Vert bouteille",
    Spanish: "Verde botella",
    Italian: "Verde bottiglia",
    Nederlands: "Flessegroen"
  },
  {
    RAL: "RAL6008",
    RGB: "54-52-42",
    HEX: "#35382E",
    German: "Braungrün",
    English: "Brown green",
    French: "Vert brun",
    Spanish: "Verde parduzco",
    Italian: "Verde brunastro",
    Nederlands: "Bruingroen"
  },
  {
    RAL: "RAL6009",
    RGB: "39-54-42",
    HEX: "#26392F",
    German: "Tannengrün",
    English: "Fir green",
    French: "Vert sapin",
    Spanish: "Verde abeto",
    Italian: "Verde abete",
    Nederlands: "Dennegroen"
  },
  {
    RAL: "RAL6010",
    RGB: "72-111-56",
    HEX: "#3E753B",
    German: "Grasgrün",
    English: "Grass green",
    French: "Vert herbe",
    Spanish: "Verde hierba",
    Italian: "Verde erba",
    Nederlands: "Grasgroen"
  },
  {
    RAL: "RAL6011",
    RGB: "105-125-88",
    HEX: "#68825B",
    German: "Resedagrün",
    English: "Reseda green",
    French: "Vert réséda",
    Spanish: "Verde reseda",
    Italian: "Verde reseda",
    Nederlands: "Resedagroen"
  },
  {
    RAL: "RAL6012",
    RGB: "48-61-58",
    HEX: "#31403D",
    German: "Schwarzgrün",
    English: "Black green",
    French: "Vert noir",
    Spanish: "Verde negruzco",
    Italian: "Verde nerastro",
    Nederlands: "Zwartgroen"
  },
  {
    RAL: "RAL6013",
    RGB: "122-118-90",
    HEX: "#797C5A",
    German: "Schilfgrün",
    English: "Reed green",
    French: "Vert jonc",
    Spanish: "Verde caña",
    Italian: "Verde canna",
    Nederlands: "Rietgroen"
  },
  {
    RAL: "RAL6014",
    RGB: "70-65-53",
    HEX: "#444337",
    German: "Gelboliv",
    English: "Yellow olive",
    French: "Olive jaune",
    Spanish: "Amarillo oliva",
    Italian: "Oliva giallastro",
    Nederlands: "Geel olijfgroen"
  },
  {
    RAL: "RAL6015",
    RGB: "60-61-54",
    HEX: "#3D403A",
    German: "Schwarzoliv",
    English: "Black olive",
    French: "Olive noir",
    Spanish: "Oliva negruzco",
    Italian: "Oliva nerastro",
    Nederlands: "Zwart olijfgroen"
  },
  {
    RAL: "RAL6016",
    RGB: "0-106-76",
    HEX: "#026A52",
    German: "Türkisgrün",
    English: "Turquoise green",
    French: "Vert turquoise",
    Spanish: "Verde turquesa",
    Italian: "Verde turchese",
    Nederlands: "Turkooisgroen"
  },
  {
    RAL: "RAL6017",
    RGB: "83-128-63",
    HEX: "#468641",
    German: "Maigrün",
    English: "May green",
    French: "Vert mai",
    Spanish: "Verde mayo",
    Italian: "Verde maggio",
    Nederlands: "Meigroen"
  },
  {
    RAL: "RAL6018",
    RGB: "89-154-57",
    HEX: "#48A43F",
    German: "Gelbgrün",
    English: "Yellow green",
    French: "Vert jaune",
    Spanish: "Verde amarillento",
    Italian: "Verde giallastro",
    Nederlands: "Geelgroen"
  },
  {
    RAL: "RAL6019",
    RGB: "183-206-172",
    HEX: "#B7D9B1",
    German: "Weißgrün",
    English: "Pastel green",
    French: "Vert blanc",
    Spanish: "Verde lanquecino",
    Italian: "Verde biancastro",
    Nederlands: "Witgroen"
  },
  {
    RAL: "RAL6020",
    RGB: "54-66-47",
    HEX: "#354733",
    German: "Chromoxidgrün",
    English: "Chrome green",
    French: "Vert oxyde chromique",
    Spanish: "Verde cromo",
    Italian: "Verde cromo",
    Nederlands: "Chroom-oxydegroen"
  },
  {
    RAL: "RAL6021",
    RGB: "135-154-119",
    HEX: "#86A47C",
    German: "Blassgrün",
    English: "Pale green",
    French: "Vert pâle",
    Spanish: "Verde pálido",
    Italian: "Verde pallido",
    Nederlands: "Bleekgroen"
  },
  {
    RAL: "RAL6022",
    RGB: "57-51-39",
    HEX: "#3E3C32",
    German: "Braunoliv",
    English: "Olive drab",
    French: "Olive brun",
    Spanish: "Oliva parduzco",
    Italian: "Oliva brunastro",
    Nederlands: "Bruin olijfgroen"
  },
  {
    RAL: "RAL6024",
    RGB: "0-132-80",
    HEX: "#008754",
    German: "Verkehrsgrün",
    English: "Traffic green",
    French: "Vert signalisation",
    Spanish: "Verde tráfico",
    Italian: "Verde traffico",
    Nederlands: "Verkeersgroen"
  },
  {
    RAL: "RAL6025",
    RGB: "90-110-59",
    HEX: "#53753C",
    German: "Farngrün",
    English: "Fern green",
    French: "Vert fougère",
    Spanish: "Verde helecho",
    Italian: "Verde felce",
    Nederlands: "Varengroen"
  },
  {
    RAL: "RAL6026",
    RGB: "0-95-78",
    HEX: "#005D52",
    German: "Opalgrün",
    English: "Opal green",
    French: "Vert opale",
    Spanish: "Verde opalo",
    Italian: "Verde opale",
    Nederlands: "Opaalgroen"
  },
  {
    RAL: "RAL6027",
    RGB: "128-186-181",
    HEX: "#81C0BB",
    German: "Lichtgrün",
    English: "Light green",
    French: "Vert clair",
    Spanish: "Verde luminoso",
    Italian: "Verde chiaro",
    Nederlands: "Lichtgroen"
  },
  {
    RAL: "RAL6028",
    RGB: "48-84-66",
    HEX: "#2D5546",
    German: "Kieferngrün",
    English: "Pine green",
    French: "Vert pin",
    Spanish: "Verde pino",
    Italian: "Verde pino",
    Nederlands: "Pijnboomgroen"
  },
  {
    RAL: "RAL6029",
    RGB: "0-112-60",
    HEX: "#007243",
    German: "Minzgrün",
    English: "Mint green",
    French: "Vert menthe",
    Spanish: "Verde menta",
    Italian: "Verde menta",
    Nederlands: "Mintgroen"
  },
  {
    RAL: "RAL6032",
    RGB: "28-128-81",
    HEX: "#0F8558",
    German: "Signalgrün",
    English: "Signal green",
    French: "Vert de sécurité",
    Spanish: "Verde señales",
    Italian: "Verde segnale",
    Nederlands: "Signaalgroen"
  },
  {
    RAL: "RAL6033",
    RGB: "72-135-127",
    HEX: "#478A84",
    German: "Minttürkis",
    English: "Mint turquoise",
    French: "Turquoise menthe",
    Spanish: "Turquesa menta",
    Italian: "Turchese menta",
    Nederlands: "Mintturquoise"
  },
  {
    RAL: "RAL6034",
    RGB: "124-173-172",
    HEX: "#7FB0B2",
    German: "Pastelltürkis",
    English: "Pastel turquoise",
    French: "Turquoise pastel",
    Spanish: "Turquesa pastel",
    Italian: "Turchese pastello",
    Nederlands: "Pastelturquoise"
  },
  {
    RAL: "RAL6035",
    RGB: "19-77-36",
    HEX: "#1B542C",
    German: "Perlgrün",
    English: "Pearl green",
    French: "Vert nacré",
    Spanish: "Verde perlado",
    Italian: "Verde perlato",
    Nederlands: "Parelmoer-donkergroen"
  },
  {
    RAL: "RAL6036",
    RGB: "7-88-75",
    HEX: "#005D4C",
    German: "Perlopalgrün",
    English: "Pearl opal green",
    French: "Vert opal nacré",
    Spanish: "Verde ópalo perlado",
    Italian: "Verde opalo perlato",
    Nederlands: "Parelmoer-lichtgroen"
  },
  {
    RAL: "RAL6037",
    RGB: "0-140-39",
    HEX: "#25E712",
    German: "Reingrün",
    English: "Pure green",
    French: "Vert pur",
    Spanish: "Verde puro",
    Italian: "Verde puro",
    Nederlands: "Zuivergroen"
  },
  {
    RAL: "RAL6038",
    RGB: "0-182-18",
    HEX: "#00F700",
    German: "Leuchtgrün",
    English: "Luminous green",
    French: "Vert brillant",
    Spanish: "Verde brillante",
    Italian: "Verde brillante",
    Nederlands: "Briljantgroen"
  },
  {
    RAL: "RAL7000",
    RGB: "123-136-142",
    HEX: "#7E8B92",
    German: "Fehgrau",
    English: "Squirrel grey",
    French: "Gris petit-gris",
    Spanish: "Gris ardilla",
    Italian: "Grigio vaio",
    Nederlands: "Pelsgrijs"
  },
  {
    RAL: "RAL7001",
    RGB: "142-150-157",
    HEX: "#8F999F",
    German: "Silbergrau",
    English: "Silver grey",
    French: "Gris argent",
    Spanish: "Gris plata",
    Italian: "Grigio argento",
    Nederlands: "Zilvergrijs"
  },
  {
    RAL: "RAL7002",
    RGB: "127-120-99",
    HEX: "#817F68",
    German: "Olivgrau",
    English: "Olive grey",
    French: "Gris olive",
    Spanish: "Gris oliva",
    Italian: "Grigio olivastro",
    Nederlands: "Olijfgrijs"
  },
  {
    RAL: "RAL7003",
    RGB: "120-119-105",
    HEX: "#7A7B6D",
    German: "Moosgrau",
    English: "Moss grey",
    French: "Gris mousse",
    Spanish: "Gris musgo",
    Italian: "Grigio muschio",
    Nederlands: "Mosgrijs"
  },
  {
    RAL: "RAL7004",
    RGB: "155-155-155",
    HEX: "#9EA0A1",
    German: "Signalgrau",
    English: "Signal grey",
    French: "Gris de sécurité",
    Spanish: "Gris señales",
    Italian: "Grigio segnale",
    Nederlands: "Signaalgrijs"
  },
  {
    RAL: "RAL7005",
    RGB: "107-110-107",
    HEX: "#6B716F",
    German: "Mausgrau",
    English: "Mouse grey",
    French: "Gris souris",
    Spanish: "Gris ratón",
    Italian: "Grigio topo",
    Nederlands: "Muisgrijs"
  },
  {
    RAL: "RAL7006",
    RGB: "117-106-94",
    HEX: "#756F61",
    German: "Beigegrau",
    English: "Beige grey",
    French: "Gris beige",
    Spanish: "Gris beige",
    Italian: "Grigio beige",
    Nederlands: "Beigegrijs"
  },
  {
    RAL: "RAL7008",
    RGB: "114-95-60",
    HEX: "#746643",
    German: "Khakigrau",
    English: "Khaki grey",
    French: "Gris kaki",
    Spanish: "Gris caqui",
    Italian: "Grigio kaki",
    Nederlands: "Kakigrijs"
  },
  {
    RAL: "RAL7009",
    RGB: "92-96-88",
    HEX: "#5B6259",
    German: "Grüngrau",
    English: "Green grey",
    French: "Gris vert",
    Spanish: "Gris verdoso",
    Italian: "Grigio verdastro",
    Nederlands: "Groengrijs"
  },
  {
    RAL: "RAL7010",
    RGB: "88-92-86",
    HEX: "#575D57",
    German: "Zeltgrau",
    English: "Tarpaulin grey",
    French: "Gris tente",
    Spanish: "Gris lona",
    Italian: "Grigio tenda",
    Nederlands: "Zeildoekgrijs"
  },
  {
    RAL: "RAL7011",
    RGB: "83-89-93",
    HEX: "#555D61",
    German: "Eisengrau",
    English: "Iron grey",
    French: "Gris fer",
    Spanish: "Gris hierro",
    Italian: "Grigio ferro",
    Nederlands: "IJzergrijs"
  },
  {
    RAL: "RAL7012",
    RGB: "88-93-94",
    HEX: "#596163",
    German: "Basaltgrau",
    English: "Basalt grey",
    French: "Gris basalte",
    Spanish: "Gris basalto",
    Italian: "Grigio basalto",
    Nederlands: "Bazaltgrijs"
  },
  {
    RAL: "RAL7013",
    RGB: "86-80-68",
    HEX: "#555548",
    German: "Braungrau",
    English: "Brown grey",
    French: "Gris brun",
    Spanish: "Gris parduzco",
    Italian: "Grigio brunastro",
    Nederlands: "Bruingrijs"
  },
  {
    RAL: "RAL7015",
    RGB: "80-83-89",
    HEX: "#51565C",
    German: "Schiefergrau",
    English: "Slate grey",
    French: "Gris foncé",
    Spanish: "Gris pizarra",
    Italian: "Grigio ardesia",
    Nederlands: "Leigrijs"
  },
  {
    RAL: "RAL7016",
    RGB: "56-62-66",
    HEX: "#373F43",
    German: "Anthrazitgrau",
    English: "Anthracite grey",
    French: "Gris anthracite",
    Spanish: "Gris antracita",
    Italian: "Grigio antracite",
    Nederlands: "Antracietgrijs"
  },
  {
    RAL: "RAL7021",
    RGB: "48-50-52",
    HEX: "#2E3234",
    German: "Schwarzgrau",
    English: "Black grey",
    French: "Gris noir",
    Spanish: "Gris negruzco",
    Italian: "Grigio nerastro",
    Nederlands: "Zwartgrijs"
  },
  {
    RAL: "RAL7022",
    RGB: "76-74-68",
    HEX: "#4B4D46",
    German: "Umbragrau",
    English: "Umbra grey",
    French: "Gris terre d’ombre",
    Spanish: "Gris sombra",
    Italian: "Grigio ombra",
    Nederlands: "Ombergrijs"
  },
  {
    RAL: "RAL7023",
    RGB: "127-128-118",
    HEX: "#818479",
    German: "Betongrau",
    English: "Concrete grey",
    French: "Gris béton",
    Spanish: "Gris hormigón",
    Italian: "Grigio calcestruzzo",
    Nederlands: "Betongrijs"
  },
  {
    RAL: "RAL7024",
    RGB: "70-73-79",
    HEX: "#474A50",
    German: "Graphitgrau",
    English: "Graphite grey",
    French: "Gris graphite",
    Spanish: "Gris grafita",
    Italian: "Grigio grafite",
    Nederlands: "Grafietgrijs"
  },
  {
    RAL: "RAL7026",
    RGB: "56-67-69",
    HEX: "#374447",
    German: "Granitgrau",
    English: "Granite grey",
    French: "Gris granit",
    Spanish: "Gris granito",
    Italian: "Grigio granito",
    Nederlands: "Granietgrijs"
  },
  {
    RAL: "RAL7030",
    RGB: "145-142-133",
    HEX: "#939388",
    German: "Steingrau",
    English: "Stone grey",
    French: "Gris pierre",
    Spanish: "Gris piedra",
    Italian: "Grigio pietra",
    Nederlands: "Steengrijs"
  },
  {
    RAL: "RAL7031",
    RGB: "93-104-109",
    HEX: "#5D6970",
    German: "Blaugrau",
    English: "Blue grey",
    French: "Gris bleu",
    Spanish: "Gris azulado",
    Italian: "Grigio bluastro",
    Nederlands: "Blauwgrijs"
  },
  {
    RAL: "RAL7032",
    RGB: "180-176-161",
    HEX: "#B9B9A8",
    German: "Kieselgrau",
    English: "Pebble grey",
    French: "Gris silex",
    Spanish: "Gris guijarro",
    Italian: "Grigio ghiaia",
    Nederlands: "Kiezelgrijs"
  },
  {
    RAL: "RAL7033",
    RGB: "126-130-116",
    HEX: "#818979",
    German: "Zementgrau",
    English: "Cement grey",
    French: "Gris ciment",
    Spanish: "Gris cemento",
    Italian: "Grigio cemento",
    Nederlands: "Cementgrijs"
  },
  {
    RAL: "RAL7034",
    RGB: "144-136-111",
    HEX: "#939176",
    German: "Gelbgrau",
    English: "Yellow grey",
    French: "Gris jaune",
    Spanish: "Gris amarillento",
    Italian: "Grigio giallastro",
    Nederlands: "Geelgrijs"
  },
  {
    RAL: "RAL7035",
    RGB: "197-199-196",
    HEX: "#CBD0CC",
    German: "Lichtgrau",
    English: "Light grey",
    French: "Gris clair",
    Spanish: "Gris luminoso",
    Italian: "Grigio luce",
    Nederlands: "Lichtgrijs"
  },
  {
    RAL: "RAL7036",
    RGB: "151-147-146",
    HEX: "#9A9697",
    German: "Platingrau",
    English: "Platinum grey",
    French: "Gris platine",
    Spanish: "Gris platino",
    Italian: "Grigio platino",
    Nederlands: "Platinagrijs"
  },
  {
    RAL: "RAL7037",
    RGB: "122-123-122",
    HEX: "#7C7F7E",
    German: "Staubgrau",
    English: "Dusty grey",
    French: "Gris poussière",
    Spanish: "Gris polvo",
    Italian: "Grigio polvere",
    Nederlands: "Stofgrijs"
  },
  {
    RAL: "RAL7038",
    RGB: "175-177-169",
    HEX: "#B4B8B0",
    German: "Achatgrau",
    English: "Agate grey",
    French: "Gris agate",
    Spanish: "Gris ágata",
    Italian: "Grigio agata",
    Nederlands: "Agaatgrijs"
  },
  {
    RAL: "RAL7039",
    RGB: "106-102-94",
    HEX: "#6B695F",
    German: "Quarzgrau",
    English: "Quartz grey",
    French: "Gris quartz",
    Spanish: "Gris cuarzo",
    Italian: "Grigio quarzo",
    Nederlands: "Kwartsgrijs"
  },
  {
    RAL: "RAL7040",
    RGB: "152-158-161",
    HEX: "#9DA3A6",
    German: "Fenstergrau",
    English: "Window grey",
    French: "Gris fenêtre",
    Spanish: "Gris ventana",
    Italian: "Grigio finestra",
    Nederlands: "Venstergrijs"
  },
  {
    RAL: "RAL7042",
    RGB: "142-146-145",
    HEX: "#8F9695",
    German: "Verkehrsgrau A",
    English: "Traffic grey A",
    French: "Gris signalisation A",
    Spanish: "Gris tráfico A",
    Italian: "Grigio traffico A",
    Nederlands: "Verkeesgrijs A"
  },
  {
    RAL: "RAL7043",
    RGB: "79-82-80",
    HEX: "#4E5451",
    German: "Verkehrsgrau B",
    English: "Traffic grey B",
    French: "Gris signalisation B",
    Spanish: "Gris tráfico B",
    Italian: "Grigio traffico B",
    Nederlands: "Verkeersgrijs B"
  },
  {
    RAL: "RAL7044",
    RGB: "182-179-168",
    HEX: "#BDBDB2",
    German: "Seidengrau",
    English: "Silk grey",
    French: "Gris soie",
    Spanish: "Gris seda",
    Italian: "Grigio seta",
    Nederlands: "Zijdegrijs"
  },
  {
    RAL: "RAL7045",
    RGB: "142-146-149",
    HEX: "#91969A",
    German: "Telegrau 1",
    English: "Telegrey 1",
    French: "Telegris 1",
    Spanish: "Gris tele 1",
    Italian: "Tele grigio 1",
    Nederlands: "Telegrijs 1"
  },
  {
    RAL: "RAL7046",
    RGB: "127-134-138",
    HEX: "#82898E",
    German: "Telegrau 2",
    English: "Telegrey 2",
    French: "Telegris 2",
    Spanish: "Gris tele 2",
    Italian: "Tele grigio 2",
    Nederlands: "Telegrijs 2"
  },
  {
    RAL: "RAL7047",
    RGB: "200-200-199",
    HEX: "#CFD0CF",
    German: "Telegrau 4",
    English: "Telegrey 4",
    French: "Telegris 4",
    Spanish: "Gris tele 4",
    Italian: "Tele grigio 4",
    Nederlands: "Telegrijs 4"
  },
  {
    RAL: "RAL7048",
    RGB: "128-123-115",
    HEX: "#888175",
    German: "Perlmausgrau",
    English: "Pearl mouse grey",
    French: "Gris souris nacré",
    Spanish: "Gris musgo perlado",
    Italian: "Grigio topo perlato",
    Nederlands: "Parelmoer-muisgrijs"
  },
  {
    RAL: "RAL8000",
    RGB: "134-106-62",
    HEX: "#887142",
    German: "Grünbraun",
    English: "Green brown",
    French: "Brun vert",
    Spanish: "Pardo verdoso",
    Italian: "Marrone verdastro",
    Nederlands: "Groenbruin"
  },
  {
    RAL: "RAL8001",
    RGB: "153-99-43",
    HEX: "#9C6B30",
    German: "Ockerbraun",
    English: "Ochre brown",
    French: "Brun terre de Sienne",
    Spanish: "Pardo ocre",
    Italian: "Marrone ocra",
    Nederlands: "Okerbruin"
  },
  {
    RAL: "RAL8002",
    RGB: "119-77-62",
    HEX: "#7B5141",
    German: "Signalbraun",
    English: "Signal brown",
    French: "Brun de sécurité",
    Spanish: "Marrón señales",
    Italian: "Marrone segnale",
    Nederlands: "Signaalbruin"
  },
  {
    RAL: "RAL8003",
    RGB: "124-75-39",
    HEX: "#80542F",
    German: "Lehmbraun",
    English: "Clay brown",
    French: "Brun argile",
    Spanish: "Pardo arcilla",
    Italian: "Marrone fango",
    Nederlands: "Leembruin"
  },
  {
    RAL: "RAL8004",
    RGB: "138-73-49",
    HEX: "#8F4E35",
    German: "Kupferbraun",
    English: "Copper brown",
    French: "Brun cuivré",
    Spanish: "Pardo cobre",
    Italian: "Marrone rame",
    Nederlands: "Koperbruin"
  },
  {
    RAL: "RAL8007",
    RGB: "109-70-43",
    HEX: "#6F4A2F",
    German: "Rehbraun",
    English: "Fawn brown",
    French: "Brun fauve",
    Spanish: "Pardo corzo",
    Italian: "Marrone capriolo",
    Nederlands: "Reebruin"
  },
  {
    RAL: "RAL8008",
    RGB: "111-74-37",
    HEX: "#6F4F28",
    German: "Olivbraun",
    English: "Olive brown",
    French: "Brun olive",
    Spanish: "Pardo oliva",
    Italian: "Marrone oliva",
    Nederlands: "Olijfbruin"
  },
  {
    RAL: "RAL8011",
    RGB: "88-56-39",
    HEX: "#5A3A29",
    German: "Nussbraun",
    English: "Nut brown",
    French: "Brun noisette",
    Spanish: "Pardo nuez",
    Italian: "Marrone noce",
    Nederlands: "Notebruin"
  },
  {
    RAL: "RAL8012",
    RGB: "100-51-43",
    HEX: "#673831",
    German: "Rotbraun",
    English: "Red brown",
    French: "Brun rouge",
    Spanish: "Pardo rojo",
    Italian: "Marrone rossiccio",
    Nederlands: "Roodbruin"
  },
  {
    RAL: "RAL8014",
    RGB: "72-53-38",
    HEX: "#49392D",
    German: "Sepiabraun",
    English: "Sepia brown",
    French: "Brun sépia",
    Spanish: "Sepia",
    Italian: "Marrone seppia",
    Nederlands: "Sepiabruin"
  },
  {
    RAL: "RAL8015",
    RGB: "93-47-39",
    HEX: "#633A34",
    German: "Kastanienbraun",
    English: "Chestnut brown",
    French: "Marron",
    Spanish: "Castaño",
    Italian: "Marrone castagna",
    Nederlands: "Kastanjebruin"
  },
  {
    RAL: "RAL8016",
    RGB: "75-43-32",
    HEX: "#4C2F26",
    German: "Mahagonibraun",
    English: "Mahogany brown",
    French: "Brun acajou",
    Spanish: "Caoba",
    Italian: "Marrone mogano",
    Nederlands: "Mahoniebruin"
  },
  {
    RAL: "RAL8017",
    RGB: "67-47-41",
    HEX: "#44322D",
    German: "Schokoladen-braun",
    English: "Chocolate brown",
    French: "Brun chocolat",
    Spanish: "Chocolate",
    Italian: "Marrone cioccolata",
    Nederlands: "Chocoladebruin"
  },
  {
    RAL: "RAL8019",
    RGB: "61-54-53",
    HEX: "#3F3A3A",
    German: "Graubraun",
    English: "Grey brown",
    French: "Brun gris",
    Spanish: "Pardo grisáceo",
    Italian: "Marrone grigiastro",
    Nederlands: "Grijsbruin"
  },
  {
    RAL: "RAL8022",
    RGB: "26-23-25",
    HEX: "#211F20",
    German: "Schwarzbraun",
    English: "Black brown",
    French: "Brun noir",
    Spanish: "Pardo negruzco",
    Italian: "Marrone nerastro",
    Nederlands: "Zwartbruin"
  },
  {
    RAL: "RAL8023",
    RGB: "160-87-41",
    HEX: "#A65E2F",
    German: "Orangebraun",
    English: "Orange brown",
    French: "Brun orangé",
    Spanish: "Pardo anaranjado",
    Italian: "Marrone arancio",
    Nederlands: "Oranjebruin"
  },
  {
    RAL: "RAL8024",
    RGB: "118-80-56",
    HEX: "#79553C",
    German: "Beigebraun",
    English: "Beige brown",
    French: "Brun beige",
    Spanish: "Pardo beige",
    Italian: "Marrone beige",
    Nederlands: "Beigebruin"
  },
  {
    RAL: "RAL8025",
    RGB: "115-88-71",
    HEX: "#755C49",
    German: "Blassbraun",
    English: "Pale brown",
    French: "Brun pâle",
    Spanish: "Pardo pálido",
    Italian: "Marrone pallido",
    Nederlands: "Bleekbruin"
  },
  {
    RAL: "RAL8028",
    RGB: "79-58-42",
    HEX: "#4E3B2B",
    German: "Terrabraun",
    English: "Terra brown",
    French: "Brun terre",
    Spanish: "Marrón tierra",
    Italian: "Marrone terra",
    Nederlands: "Terrabruin"
  },
  {
    RAL: "RAL8029",
    RGB: "125-64-49",
    HEX: "#773C27",
    German: "Perlkupfer",
    English: "Pearl copper",
    French: "Cuivre nacré",
    Spanish: "Cobre perlado",
    Italian: "Rame perlato",
    Nederlands: "Parelmoerkoper"
  },
  {
    RAL: "RAL9001",
    RGB: "231-225-210",
    HEX: "#EFEBDC",
    German: "Cremeweiß",
    English: "Cream",
    French: "Blanc crème",
    Spanish: "Blanco crema",
    Italian: "Bianco crema",
    Nederlands: "Crèmewit"
  },
  {
    RAL: "RAL9002",
    RGB: "214-213-203",
    HEX: "#DDDED4",
    German: "Grauweiß",
    English: "Grey white",
    French: "Blanc gris",
    Spanish: "Blanco grisáceo",
    Italian: "Bianco grigiastro",
    Nederlands: "Grijswit"
  },
  {
    RAL: "RAL9003",
    RGB: "236-236-231",
    HEX: "#F4F8F4",
    German: "Signalweiß",
    English: "Signal white",
    French: "Blanc de sécurité",
    Spanish: "Blanco señales",
    Italian: "Bianco segnale",
    Nederlands: "Signaalwit"
  },
  {
    RAL: "RAL9004",
    RGB: "43-43-44",
    HEX: "#2E3032",
    German: "Signalschwarz",
    English: "Signal black",
    French: "Noir de sécurité",
    Spanish: "Negro señales",
    Italian: "Nero segnale",
    Nederlands: "Signaalzwart"
  },
  {
    RAL: "RAL9005",
    RGB: "14-14-16",
    HEX: "#0A0A0D",
    German: "Tiefschwarz",
    English: "Jet black",
    French: "Noir foncé",
    Spanish: "Negro intenso",
    Italian: "Nero intenso",
    Nederlands: "Gitzwart"
  },
  {
    RAL: "RAL9006",
    RGB: "161-161-160",
    HEX: "#A5A8A6",
    German: "Weißaluminium",
    English: "White aluminium",
    French: "Aluminium blanc",
    Spanish: "Aluminio blanco",
    Italian: "Aluminio brillante",
    Nederlands: "Blank aluminiumkleurig"
  },
  {
    RAL: "RAL9007",
    RGB: "134-133-129",
    HEX: "#8F8F8C",
    German: "Graualuminium",
    English: "Grey aluminium",
    French: "Aluminium gris",
    Spanish: "Aluminio gris",
    Italian: "Aluminio grigiastro",
    Nederlands: "Grijs aluminiumkleurig"
  },
  {
    RAL: "RAL9010",
    RGB: "240-237-225",
    HEX: "#F7F9EF",
    German: "Reinweiß",
    English: "Pure white",
    French: "Blanc pur",
    Spanish: "Blanco puro",
    Italian: "Bianco puro",
    Nederlands: "Zuiverwit"
  },
  {
    RAL: "RAL9011",
    RGB: "39-41-43",
    HEX: "#292C2F",
    German: "Graphitschwarz",
    English: "Graphite black",
    French: "Noir graphite",
    Spanish: "Negro grafito",
    Italian: "Nero grafite",
    Nederlands: "Grafietzwart"
  },
  {
    RAL: "RAL9016",
    RGB: "240-241-234",
    HEX: "#F7FBF5",
    German: "Verkehrsweiß",
    English: "Traffic white",
    French: "Blanc signalisation",
    Spanish: "Blanco tráfico",
    Italian: "Bianco traffico",
    Nederlands: "Verkeerswit"
  },
  {
    RAL: "RAL9017",
    RGB: "42-41-42",
    HEX: "#2A2D2F",
    German: "Verkehrs-schwarz",
    English: "Traffic black",
    French: "Noir signalisation",
    Spanish: "Negro tráfico",
    Italian: "Nero traffico",
    Nederlands: "Verkeerszwart"
  },
  {
    RAL: "RAL9018",
    RGB: "199-203-196",
    HEX: "#CFD3CD",
    German: "Papyrusweiß",
    English: "Papyrus white",
    French: "Blanc papyrus",
    Spanish: "Blanco papiro",
    Italian: "Bianco papiro",
    Nederlands: "Papyruswit"
  },
  {
    RAL: "RAL9022",
    RGB: "133-133-131",
    HEX: "#9C9C9C",
    German: "Perlhellgrau",
    English: "Pearl light grey",
    French: "Gris clair nacré",
    Spanish: "Gris claro perlado",
    Italian: "Grigio chiaro perlato",
    Nederlands: "Parelmoer-lichtgrijs"
  },
  {
    RAL: "RAL9023",
    RGB: "121-123-123",
    HEX: "#7E8182",
    German: "Perldunkelgrau",
    English: "Pearl dark grey",
    French: "Gris fonçé nacré",
    Spanish: "Gris oscuro perlado",
    Italian: "Grigio scuro perlato",
    Nederlands: "Parelmoer-donkergrijs"
  }
];

module.exports = {RalPalette}
