/** Declaration file generated by dts-gen */

export const hex: string[];

export const rals: string[];

export function toHex(ral: string | number): string;

export function toRal(hex: string): string;

